# Generated by Codex on 2026-06-01

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KaspaFederation",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("mainnet", "Mainnet"),
                            ("testnet", "Testnet"),
                            ("devnet", "Devnet"),
                            ("simnet", "Simnet"),
                        ],
                        max_length=16,
                    ),
                ),
                ("xpubs", models.JSONField(default=list)),
                ("xpub_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("threshold", models.PositiveSmallIntegerField()),
                ("ecdsa", models.BooleanField(default=False)),
                ("origin", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="KaspaTxProposal",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "proposal_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "format",
                    models.CharField(default="kaspawallet_pst_v1", max_length=32),
                ),
                ("unsigned_bundle_hex", models.TextField()),
                ("merged_bundle_hex", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("broadcasted", "Broadcasted"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("tx_ids", models.JSONField(default=list)),
                ("input_outpoints", models.JSONField(default=list)),
                ("outputs", models.JSONField(default=list)),
                ("fee_sompi", models.BigIntegerField(blank=True, null=True)),
                ("mass", models.BigIntegerField(blank=True, null=True)),
                ("signatures_required", models.PositiveSmallIntegerField()),
                (
                    "signatures_collected",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("proposed_by", models.CharField(blank=True, default="", max_length=255)),
                ("origin", models.JSONField(default=dict)),
                ("broadcast_tx_ids", models.JSONField(default=list)),
                ("broadcast_error", models.TextField(blank=True, null=True)),
                (
                    "federation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tx_proposals",
                        to="kaspa.kaspafederation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="KaspaFederationParticipant",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("root_xpub", models.TextField()),
                ("cosigner_index", models.PositiveSmallIntegerField()),
                (
                    "federation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="kaspa.kaspafederation",
                    ),
                ),
            ],
            options={
                "ordering": ["cosigner_index"],
            },
        ),
        migrations.CreateModel(
            name="KaspaTxSignature",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("signer", models.CharField(blank=True, default="", max_length=255)),
                ("submission_hash", models.CharField(max_length=64)),
                ("signed_bundle_hex", models.TextField()),
                ("added_signatures", models.JSONField(default=list)),
                ("signature_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tx_signatures",
                        to="kaspa.kaspafederationparticipant",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="kaspa.kaspatxproposal",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="KaspaBroadcastAttempt",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tx_ids", models.JSONField(default=list)),
                ("rpc_url", models.CharField(blank=True, default="", max_length=255)),
                ("error", models.TextField(blank=True, null=True)),
                ("success", models.BooleanField(db_index=True, default=False)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_attempts",
                        to="kaspa.kaspatxproposal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddIndex(
            model_name="kaspatxproposal",
            index=models.Index(
                fields=["federation", "status", "-created"],
                name="kaspa_proposal_fed_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="kaspafederation",
            constraint=models.UniqueConstraint(
                fields=("network", "xpub_fingerprint", "threshold", "ecdsa"),
                name="unique_kaspa_federation",
            ),
        ),
        migrations.AddConstraint(
            model_name="kaspafederationparticipant",
            constraint=models.UniqueConstraint(
                fields=("federation", "root_xpub"),
                name="unique_kaspa_participant_xpub",
            ),
        ),
        migrations.AddConstraint(
            model_name="kaspafederationparticipant",
            constraint=models.UniqueConstraint(
                fields=("federation", "cosigner_index"),
                name="unique_kaspa_participant_cosigner_index",
            ),
        ),
        migrations.AddConstraint(
            model_name="kaspatxsignature",
            constraint=models.UniqueConstraint(
                fields=("proposal", "submission_hash"),
                name="unique_kaspa_signature_submission",
            ),
        ),
    ]
