# Generated by Codex on 2026-06-01

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("kaspa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KaspaExitBatch",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("mainnet", "Mainnet"),
                            ("testnet", "Testnet"),
                            ("devnet", "Devnet"),
                            ("simnet", "Simnet"),
                        ],
                        max_length=16,
                    ),
                ),
                ("l2_chain_id", models.PositiveIntegerField(db_index=True)),
                ("from_block", models.PositiveBigIntegerField()),
                ("to_block", models.PositiveBigIntegerField()),
                (
                    "finalized_at_block",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("observing", "Observing"),
                            ("verified", "Verified"),
                            ("proposed", "Proposed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="observing",
                        max_length=16,
                    ),
                ),
                (
                    "evidence_hash",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("total_exits", models.PositiveIntegerField(default=0)),
                ("total_amount_sompi", models.BigIntegerField(default=0)),
                ("canonical_bridge_address", models.CharField(max_length=128)),
                (
                    "canonical_bridge_script_public_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "canonical_derivation_path",
                    models.CharField(default="m/0/0/1", max_length=64),
                ),
                ("threshold", models.PositiveSmallIntegerField()),
                ("xpub_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("checks", models.JSONField(default=dict)),
                ("artifact_hashes", models.JSONField(default=dict)),
                ("evidence", models.JSONField(default=dict)),
                (
                    "federation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_batches",
                        to="kaspa.kaspafederation",
                    ),
                ),
            ],
            options={
                "ordering": ["-to_block", "-created"],
            },
        ),
        migrations.CreateModel(
            name="KaspaExitRequest",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_id", models.PositiveBigIntegerField()),
                ("message_id", models.CharField(db_index=True, max_length=66)),
                ("block_number", models.PositiveBigIntegerField(db_index=True)),
                ("transaction_hash", models.CharField(db_index=True, max_length=66)),
                ("log_index", models.PositiveIntegerField(blank=True, null=True)),
                ("tree_index", models.PositiveBigIntegerField(blank=True, null=True)),
                ("recipient_address", models.CharField(max_length=128)),
                ("amount_sompi", models.BigIntegerField()),
                ("burn_wei", models.CharField(blank=True, default="", max_length=80)),
                (
                    "origin_burner_address",
                    models.CharField(blank=True, default="", max_length=42),
                ),
                ("dispatch_message", models.TextField(blank=True, default="")),
                ("dispatch_decoded", models.JSONField(default=dict)),
                ("raw", models.JSONField(default=dict)),
                ("checks", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(db_index=True, default="success", max_length=32),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_requests",
                        to="kaspa.kaspaexitbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["block_number", "log_index", "request_id"],
            },
        ),
        migrations.AddField(
            model_name="kaspatxproposal",
            name="exit_batch",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tx_proposal",
                to="kaspa.kaspaexitbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="kaspaexitbatch",
            index=models.Index(
                fields=["network", "status", "to_block"],
                name="kaspa_exit_batch_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="kaspaexitbatch",
            constraint=models.UniqueConstraint(
                fields=("federation", "l2_chain_id", "from_block", "to_block"),
                name="unique_kaspa_exit_batch_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="kaspaexitrequest",
            constraint=models.UniqueConstraint(
                fields=("batch", "request_id"),
                name="unique_kaspa_exit_request_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="kaspaexitrequest",
            constraint=models.UniqueConstraint(
                fields=("batch", "message_id"),
                name="unique_kaspa_exit_message_id",
            ),
        ),
    ]
