# Generated by Codex on 2026-06-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kaspa", "0002_kaspa_exit_batches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kaspatxproposal",
            name="exit_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tx_proposals",
                to="kaspa.kaspaexitbatch",
            ),
        ),
    ]
