# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kaspa", "0003_allow_multiple_exit_batch_proposals"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="kaspaexitbatch",
            name="unique_kaspa_exit_batch_window",
        ),
        migrations.AddConstraint(
            model_name="kaspaexitbatch",
            constraint=models.UniqueConstraint(
                fields=(
                    "federation",
                    "l2_chain_id",
                    "from_block",
                    "to_block",
                    "evidence_hash",
                ),
                name="unique_kaspa_exit_batch_window",
            ),
        ),
    ]
